Working towards adding syscall tracing for arm.
commit 8ef102c6b4bc996ff96ca52b34775fe931ec90c9
Author: Wade Farnsworth <wade_farnsworth@mentor.com>
Date:   Tue Oct 2 17:08:30 2012 +0100

    ARM: 7548/1: include linux/sched.h in syscall.h

    The syscall tracing patch introduces a compile bug in lttng-modules
    when the latter calls syscall_get_nr(), similar to the following:

    <path-to-linux>/arch/arm/include/asm/syscall.h:21:2: error: implicit declaration of function 'task_thread_info' [-Werror=implicit-function-declaration]

    The issue is that we are using task_thread_info() in the
    syscall_get_nr() function in asm/syscall.h, but not explicitly
    including sched.h from this file, so we can expect this bug might
    surface any time that syscall_get_nr() is called.

    Explicitly including sched.h solves the problem.

    Cc: <stable@vger.kernel.org> [3.5, 3.6]
    Signed-off-by: Wade Farnsworth <wade_farnsworth@mentor.com>
    Acked-by: Will Deacon <will.deacon@arm.com>
    Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

Also, handled merge conflicts from b4874a3d298606c20118d1ead73235439bbc2823 Merge branch 'fixes' into for-linus